/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManager;
import java.awt.Rectangle;
import java.awt.event.*;
import java.sql.*;
import static LibraryManager.Host.con;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PATIR
 */
public class JD_search extends javax.swing.JDialog {
    
    Vector data=new Vector();
    Vector title=new Vector();
    
    //JTable jTable1=new JTable();
    int judge;
    /**
     * Creates new form JD_search
     */
    public JD_search(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("图书管理系统-查询功能");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("按");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("书名");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("书号");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("类型");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("作者");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("查询");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuBar2.setToolTipText("菜单栏");

        jMenu1.setText("功能");

        jMenuItem1.setText("增添书籍");
        jMenuItem1.setToolTipText("For add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("修改书籍参数");
        jMenuItem2.setToolTipText("For Update");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("删除书籍");
        jMenuItem3.setToolTipText("For delete");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setText("查询书籍");
        jMenuItem6.setToolTipText("For search");
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator1);

        jMenuItem5.setText("退出系统");
        jMenuItem5.setToolTipText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar2.add(jMenu1);

        jMenu4.setText("用户");
        jMenu4.setToolTipText("");

        jMenuItem4.setText("用户调查问卷");
        jMenuItem4.setToolTipText("Questionnaire");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);
        jMenu4.add(jSeparator2);

        jMenuItem7.setText("退出当前用户");
        jMenuItem7.setToolTipText("Quit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton5)))
                .addGap(100, 100, 100))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        judge=1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText();
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "不能为空!", "Reminding!", JOptionPane.ERROR_MESSAGE);;
            return;
        }
        if(judge==1)//按书名查询
        {
       data.clear();
       Vector<String> title = new Vector<String>();
       //String[] title={ "书名", "书号", "类型", "作者", "出版社","价格"};
       title.add("书名");
       title.add("书号");
       title.add("类型");
       title.add("作者");
       title.add("出版社");
       title.add("价格");
       
        JTable table=new JTable();
        DefaultTableModel dtm=(DefaultTableModel)table.getModel();
        dtm.setRowCount( 0 );
            try
            {
                PreparedStatement stmt=con.prepareStatement("select * from Book where cast([bookName] as nvarchar(max)) like ?");
                stmt.setString(1,"%"+name+"%");
                ResultSet rs=stmt.executeQuery();
                while(rs.next())
                {
                    Vector line=new Vector();
                    for(int i=1;i<=6;i++)
                    {
                        line.add(rs.getObject(i));
                    }
                    data.add(line);
                }

        
                rs.close();
                stmt.close();
                //con.close();
                //new JD_search(new DialogSystem(),true).setVisible(true);

            }
            catch(SQLException e)
            {
                e.printStackTrace();
            }
        //dtm.setDataVector(data, title);
        jTable1.setModel(new DefaultTableModel(data,title));
        }
        
        else if(judge==2)//按书号查询
        {
            data.clear();
       Vector<String> title = new Vector<String>();
       //String[] title={ "书名", "书号", "类型", "作者", "出版社","价格"};
       title.add("书名");
       title.add("书号");
       title.add("类型");
       title.add("作者");
       title.add("出版社");
       title.add("价格");
       
        JTable table=new JTable();
        DefaultTableModel dtm=(DefaultTableModel)table.getModel();
        dtm.setRowCount( 0 );
        Integer a=Integer.parseInt(name);
        
            try
            {
                PreparedStatement stmt=con.prepareStatement("select * from Book where bookID=?");
                stmt.setInt(1,a);
                ResultSet rs=stmt.executeQuery();
                while(rs.next())
                {
                    Vector line=new Vector();
                    for(int i=1;i<=6;i++)
                    {
                        line.add(rs.getObject(i));
                    }
                    data.add(line);
                }

        
                rs.close();
                stmt.close();
                //con.close();
                //new JD_search(new DialogSystem(),true).setVisible(true);

            }
            catch(SQLException e)
            {
                e.printStackTrace();
            }
        //dtm.setDataVector(data, title);
        jTable1.setModel(new DefaultTableModel(data,title));
        }
        
        else if(judge==3)//按类型查询
        {
            data.clear();
       Vector<String> title = new Vector<String>();
       //String[] title={ "书名", "书号", "类型", "作者", "出版社","价格"};
       title.add("书名");
       title.add("书号");
       title.add("类型");
       title.add("作者");
       title.add("出版社");
       title.add("价格");
       
        JTable table=new JTable();
        DefaultTableModel dtm=(DefaultTableModel)table.getModel();
        dtm.setRowCount( 0 );
        
            try
            {
                PreparedStatement stmt=con.prepareStatement("select * from Book where cast([bookType] as nvarchar(max))=?");
                stmt.setString(1,name);
                ResultSet rs=stmt.executeQuery();
                while(rs.next())
                {
                    Vector line=new Vector();
                    for(int i=1;i<=6;i++)
                    {
                        line.add(rs.getObject(i));
                    }
                    data.add(line);
                }

        
                rs.close();
                stmt.close();
                //con.close();
                //new JD_search(new DialogSystem(),true).setVisible(true);

            }
            catch(SQLException e)
            {
                e.printStackTrace();
            }
        //dtm.setDataVector(data, title);
        jTable1.setModel(new DefaultTableModel(data,title));
        }
        
        else if(judge==4)//按作者查询
        {
            data.clear();
       Vector<String> title = new Vector<String>();
       //String[] title={ "书名", "书号", "类型", "作者", "出版社","价格"};
       title.add("书名");
       title.add("书号");
       title.add("类型");
       title.add("作者");
       title.add("出版社");
       title.add("价格");
       
        JTable table=new JTable();
        DefaultTableModel dtm=(DefaultTableModel)table.getModel();
        dtm.setRowCount( 0 );
        
            try
            {
                PreparedStatement stmt=con.prepareStatement("select * from Book where cast([author] as nvarchar(max)) like ?");
                stmt.setString(1,"%"+name+"%");
                ResultSet rs=stmt.executeQuery();
                while(rs.next())
                {
                    Vector line=new Vector();
                    for(int i=1;i<=6;i++)
                    {
                        line.add(rs.getObject(i));
                    }
                    data.add(line);
                }

        
                rs.close();
                stmt.close();
                //con.close();
                //new JD_search(new DialogSystem(),true).setVisible(true);

            }
            catch(SQLException e)
            {
                e.printStackTrace();
            }
        //dtm.setDataVector(data, title);
        jTable1.setModel(new DefaultTableModel(data,title));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        judge=2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        judge=3;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        judge=4;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        dispose();
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jMenuItem4)
        {
            new Questionnaire().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jMenuItem3)
        {
            new JD_delete(new DialogSystem(),true).setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jMenuItem2)
        {
            new JD_update(new DialogSystem(),true).setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jMenuItem1)
        {
            new JD_add(new DialogSystem(),true).setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_search dialog = new JD_search(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
